/**
 * 대정프라방 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Autonomous Producer
 */

const STAY_CONFIG = {
  brandName: "대정프라방",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "대정프라방에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  owner: "호스트",
  businessNo: "",
  address: "제주 서귀포시 대정읍 추사로 191 1층",
  phone: "0507-1392-6012",
  email: "contact@adopter.co.kr",
  domain: "daejeong.adopter.co.kr",
  
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1124644686/home",
  instagramUrl: "",
  
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  pricing: {
    weekday: 320000,
    weekend: 360000,
    peakSurcharge: 40000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 20000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  photos: [
    {
        "src": "./img/photo_1.jpg",
        "cat": "exterior",
        "title": "대정프라방 Exterior 공간 1"
    },
    {
        "src": "./img/photo_2.jpg",
        "cat": "living",
        "title": "대정프라방 Living 공간 2"
    },
    {
        "src": "./img/photo_3.jpg",
        "cat": "bedroom",
        "title": "대정프라방 Bedroom 공간 3"
    },
    {
        "src": "./img/photo_4.jpg",
        "cat": "kitchen",
        "title": "대정프라방 Kitchen 공간 4"
    },
    {
        "src": "./img/photo_5.jpg",
        "cat": "outdoor",
        "title": "대정프라방 Outdoor 공간 5"
    },
    {
        "src": "./img/photo_6.jpg",
        "cat": "exterior",
        "title": "대정프라방 Exterior 공간 6"
    },
    {
        "src": "./img/photo_7.jpg",
        "cat": "living",
        "title": "대정프라방 Living 공간 7"
    },
    {
        "src": "./img/photo_8.jpg",
        "cat": "bedroom",
        "title": "대정프라방 Bedroom 공간 8"
    },
    {
        "src": "./img/photo_9.jpg",
        "cat": "kitchen",
        "title": "대정프라방 Kitchen 공간 9"
    }
],
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
