/**
 * 모험담 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Nightly Producer
 */

const STAY_CONFIG = {
  // 1. 브랜드 및 숙소 기본 정보
  brandName: "플루메리아 펜션",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "모험담에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  // 2. 호스트 및 연락처 정보
  owner: "호스트",
  businessNo: "",
  address: "제주 제주시 구좌읍 덕행로 377-3",
  phone: "0507-1347-3972",
  email: "contact@adopter.co.kr",
  domain: "moheomdam.adopter.co.kr",
  
  // 3. 외부 연동 링크
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1716272359/home",
  instagramUrl: "https://www.instagram.com/moheomdam",
  
  // 4. 고화질 영상 배경
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  // 5. 숙박 요금 및 연박 할인 정책
  pricing: {
    weekday: 320000,
    weekend: 350000,
    peakSurcharge: 30000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 10000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  // 6. 3대 무료 혜택
  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  // 7. 공간 구성 안내
  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  // 8. 포토 갤러리 메타데이터
  photos: [
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-19/489019409_1878714619334579_6794631701344644809_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=109&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDgwLkMzIn0%3D&_nc_ohc=VdazSHf71aYQ7kNvwGavYXl&_nc_oc=AdpCPNrHC6AgZ79t-hP5Pi42SgGt1ol4DyPnBWhSO2TGdDzMViBasLAACGEHQrgUc-U&_nc_zt=24&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQOlklHry_QeZLPFJZjeQZLnepdb6oMG0ZXskPUfcfSXVQ&oe=6AC3DABD",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 1"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t39.30808-6/363331209_18281472607126131_6691363417864367315_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=Oju4XEV7FAgQ7kNvwHXP23Z&_nc_oc=AdoRJiY-Noa6Q0xrb_Y6PAQ5maQ_6lUZAmsg5-kC3wTwZKSN7rxANTMxMGw_PMtKFk4&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=8oelkp0Ln2VvwvlLgw_liA&_nc_ss=7f60f&oh=00_AQPLUB8P6PKRqBvBrQC_jmAFM0kRu_vQZdyYq9fvz-xK2A&oe=6AC3D6CA",
        "cat": "living",
        "title": "모험담 Living 공간 2"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t39.30808-6/360112004_18280896184126131_9040237596940077301_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=C4jMd24RyGEQ7kNvwF0fcvo&_nc_oc=AdqWWcOHFfkQ7otB8hGkFCpzNYeKiUATXFV4Q9a46-PfHNvEuIFFZCKt8nzpexnQ-eQ&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=8oelkp0Ln2VvwvlLgw_liA&_nc_ss=7f60f&oh=00_AQNrtiHSq-3ot3HadvHJQi5t4Tt5HRUAnzn-6avpxDPPJw&oe=6AC3D1C1",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 3"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/575287055_18433310911108411_3712781947408340787_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=106&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=lPktuLX6sdgQ7kNvwF_v4yY&_nc_oc=Ado8U-LRx0xoOqfxOg37d9XGgIXZreJJdNSIxXMkhGvLtfyyyxP2G4kLHmr4juabxwY&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=8oelkp0Ln2VvwvlLgw_liA&_nc_ss=7f60f&oh=00_AQOYtoAz-LprTvsA5Yr5Zz1dlDDABiR6mRj-5i7g5uQj5w&oe=6AC3B205",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 4"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/569520230_18109387003580921_2726256992675315723_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=108&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=CHKZGHRRFdcQ7kNvwEuR129&_nc_oc=AdqXz7CYbzEIf5MSDFLBpC_0jc4Fk16-7uzlomLUaAxzDfy8rXuopeJHTEz41Hjke3g&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=8oelkp0Ln2VvwvlLgw_liA&_nc_ss=7f60f&oh=00_AQMOG2fCz7T_84txBdeHS3arKkOJPXNtu8LMoFKBcOzf9Q&oe=6AC3D64B",
        "cat": "outdoor",
        "title": "모험담 Outdoor 공간 5"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/567971713_18145268035428209_3844854450570344554_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=110&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=VM9igD_r8nMQ7kNvwERQxVn&_nc_oc=AdrGl8sKvo3213WvuB0lUBPVsQV5XLzmDsCBbiLMoCzwbPMzygKpQEkZPOZ1d8RFzp8&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=8oelkp0Ln2VvwvlLgw_liA&_nc_ss=7f60f&oh=00_AQPUMXSPM25iG84wT-g3ByA55bF4_4RPpICXaMxCpApcYg&oe=6AC3DB89",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 6"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/792224034_947622368356783_8801753121188179866_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=bNyJI5l0Qa0Q7kNvwEOM9LR&_nc_oc=AdpqtwAuBxhk3svwRIXi3eGkIqJdnXUn_pXuSdkBOclw5VuZYMgofGJI4dQaS0-MNvE&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=xMCkss8e3QdOvKFouArMTA&_nc_ss=7f60f&oh=00_AQMEUAttiezo3-4vVoL7OMBI8Tr6etVbO5DsrihbGPhhyw&oe=6AC3BAF3",
        "cat": "living",
        "title": "모험담 Living 공간 7"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/792717849_1378691254331198_4505427139345546628_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=108&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=th4EZmzkVxgQ7kNvwE43IRs&_nc_oc=AdoQzfSnsTbHhVx94Mu7WL8T0K1b7Jtcx79NfU_jSiuWyzg0bRBRD05w0rucW6ewvhM&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=xMCkss8e3QdOvKFouArMTA&_nc_ss=7f60f&oh=00_AQO4lkFDQ8ozCAeGo-t2DXNtIbOdgYrLLeUGh2RSZ71A5w&oe=6AC3DD03",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 8"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/785282132_1381477090186828_6466025206020088463_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=106&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=klxXO1T88DkQ7kNvwFQKys8&_nc_oc=Adr3t9fyxIIYE4Vz46dbLbqLJk66SlR8BYlIqXH5Ic13k3EjCaStoj-btL85MfWKq4U&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=xMCkss8e3QdOvKFouArMTA&_nc_ss=7f60f&oh=00_AQNGp4UPvuEnwdUliSQ8p6v0ltSQD5aebzn22McjDJSd5g&oe=6AC3B704",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 9"
    }
],

  // 9. 관리자 비밀번호
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
