/**
 * 모험담 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Nightly Producer
 */

const STAY_CONFIG = {
  // 1. 브랜드 및 숙소 기본 정보
  brandName: "dalnosi_stay",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "모험담에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  // 2. 호스트 및 연락처 정보
  owner: "호스트",
  businessNo: "",
  address: "제주 제주시 구좌읍 덕행로 377-3",
  phone: "0507-1347-3972",
  email: "contact@adopter.co.kr",
  domain: "moheomdam.adopter.co.kr",
  
  // 3. 외부 연동 링크
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1716272359/home",
  instagramUrl: "https://www.instagram.com/moheomdam",
  
  // 4. 고화질 영상 배경
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  // 5. 숙박 요금 및 연박 할인 정책
  pricing: {
    weekday: 320000,
    weekend: 350000,
    peakSurcharge: 30000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 10000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  // 6. 3대 무료 혜택
  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  // 7. 공간 구성 안내
  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  // 8. 포토 갤러리 메타데이터
  photos: [
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-19/450206968_1196106381809856_8157997333262249038_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=106&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDgwLkMzIn0%3D&_nc_ohc=E8AvODqBavcQ7kNvwEKxX_G&_nc_oc=AdqX_lNwXd8EXs5tqiP7wPGDyuo33Ef5wYRh1ccnC-Uvph001DEH2m7B8BgI10pjcdY&_nc_zt=24&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQMqAk2Jg956Zy_rpMxzufft8UxaRWefanKRiwpHNZDE9g&oe=6AC3D0CB",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 1"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-15/453003898_972004594675336_5339546191890890933_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=107&ccb=7-5&_nc_sid=acbce5&_nc_ohc=ruGuaoupIP8Q7kNvwF7_b0J&_nc_oc=Adq8YEd0juF1UKGqXG6QHKk3D8dnvO7AWfCvWg4GBmkyLvpUSv_HZ6rsVWEDxRx_bHo&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQO2a5Kl5jEtBxbxmLP2A16tv4Zmyoh7UYYM7r3HmuVKiQ&oe=6AC3BB97",
        "cat": "living",
        "title": "모험담 Living 공간 2"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-15/452899677_1152686592617123_949786569694365950_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=105&ccb=7-5&_nc_sid=acbce5&_nc_ohc=vFU3abdExXcQ7kNvwGFdhSx&_nc_oc=AdqL4On1kwcOjZrhP33Ls19yQ5OB39gVTvRBdjYUFbstTwRwGR_5dvT6B0QfLOtYLag&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQMzLRBZS_f2MB1ajhoEkiEL1rteZgWUo-tfa7VtSm9UJw&oe=6AC3D13F",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 3"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-15/453079803_363619076574847_8043203684058698736_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=101&ccb=7-5&_nc_sid=acbce5&_nc_ohc=fb9dQSAEVBsQ7kNvwHZPdet&_nc_oc=Ado332bABZxTSE4yJDUQEMvlSyTsgSUyf79JQQeLBweW1hQWTyddSnsq1Y9WZYlZQ78&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQNj114wmrFg_BVZcgtpJSZa6b2jecOchBi0Iwb8dvU1Bg&oe=6AC3BF5E",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 4"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-15/453143356_856943686331709_4266539300180588184_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=101&ccb=7-5&_nc_sid=acbce5&_nc_ohc=dY_yT1z-xCoQ7kNvwGcoTa7&_nc_oc=AdrslbPJ1wRDW8ZVg_ZtSPoDCEypSc_stR3MdMGpubhMNDOZ5NFMFmbbgu88ckSpXLE&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQNy56Pfq1jWNPg1KkciE4_arfLErxbNZS3P39fi_Nm7vQ&oe=6AC3A876",
        "cat": "outdoor",
        "title": "모험담 Outdoor 공간 5"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-15/453086744_3619723564955958_3543307150084695524_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=101&ccb=7-5&_nc_sid=acbce5&_nc_ohc=UVFh3v0w8uYQ7kNvwHyJ6ro&_nc_oc=AdqWcQ6m7pKPqKlCG0socNS_W2_ZEywszjju9ALtSVnUnmca02QOa0KzxPMVkenWVxs&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQN2P3X6kb2-LY1VHMspk9CgiSHaaN_wVV3cVIm-6WF_vQ&oe=6AC3CC30",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 6"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.75761-15/465826832_17861317206268346_1626079837232725356_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=pf4iAKSXAWEQ7kNvwFn0Cx9&_nc_oc=AdpG6liJet6-T668mk1BTUiTMeCYJpyNiZwz4EG4zdi4thDaY8nEMnMW7tYxwHkI72k&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=so2yVktUGtKuZnbPgcAPwA&_nc_ss=7f60f&oh=00_AQOFayec6E1Xgqq0NMKCkpGhiwNCd6pWt0uCejIfg10vMA&oe=6AC3ABEA",
        "cat": "living",
        "title": "모험담 Living 공간 7"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.75761-15/466082970_17861318184268346_5449579940047713868_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=104&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=0t4-H8reE_IQ7kNvwFIyAFM&_nc_oc=AdrXcygbFSZoSqEw2McmwUaMt2Jrl-fH3SJNzvi52jiPxVciMeifNzBt6rfQvWFSLfY&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=so2yVktUGtKuZnbPgcAPwA&_nc_ss=7f60f&oh=00_AQNYZaMm_IeEurxZgY10Sl__5hN3h8uXEjvafj_iboj35w&oe=6AC3D072",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 8"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.75761-15/463952712_17858609751268346_145798847186869261_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=111&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=WUW7BotT81QQ7kNvwGGZETc&_nc_oc=Adpx5OpbxPHF5-XMyU8fEZsiK1dY5S5jfRukKLS7VV4nGzFq4YubzlGLha_UNaPHHQA&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=so2yVktUGtKuZnbPgcAPwA&_nc_ss=7f60f&oh=00_AQM3wGwSugjMRH1bt-Mbln45OI0eN140AMIg4Pu281nxDw&oe=6AC3C7D3",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 9"
    }
],

  // 9. 관리자 비밀번호
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
