/**
 * 모험담 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Nightly Producer
 */

const STAY_CONFIG = {
  // 1. 브랜드 및 숙소 기본 정보
  brandName: "하루를품다",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "모험담에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  // 2. 호스트 및 연락처 정보
  owner: "호스트",
  businessNo: "",
  address: "제주 제주시 구좌읍 덕행로 377-3",
  phone: "0507-1347-3972",
  email: "contact@adopter.co.kr",
  domain: "moheomdam.adopter.co.kr",
  
  // 3. 외부 연동 링크
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1716272359/home",
  instagramUrl: "https://www.instagram.com/moheomdam",
  
  // 4. 고화질 영상 배경
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  // 5. 숙박 요금 및 연박 할인 정책
  pricing: {
    weekday: 320000,
    weekend: 350000,
    peakSurcharge: 30000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 10000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  // 6. 3대 무료 혜택
  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  // 7. 공간 구성 안내
  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  // 8. 포토 갤러리 메타데이터
  photos: [
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-19/655204687_18515755081078673_8211639653754748457_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=110&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDgwLkMzIn0%3D&_nc_ohc=NbErFnMUUn4Q7kNvwGCdZRr&_nc_oc=AdpZ_iWJhPrusx-pcbTNL0vEUcjUwVKFNC0SHKCxiualc9_yjd6Pf68QY5tMs5eOSms&_nc_zt=24&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=HZoIiLg2vC_71LIk4CmG-Q&_nc_ss=7f60f&oh=00_AQN3isnJE6gxD4pz8Y2ea9a4dFQV45xbxvG4B4jUQSvwXw&oe=6AC3BB3C",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 1"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/659009874_18518730766078673_7510768081575520398_n.webp?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=nx_2xby3H5EQ7kNvwGqyBa3&_nc_oc=AdrsyUer-L1KPMCKVpDTtIyJIKAT-uX0fwIp2Yifk9R9HUKsWs3xhZhVcfFI1scOfRU&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=5k-3-3vW8pFdTZ4v0gVdaA&_nc_ss=7f60f&oh=00_AQPVFqI2WEGUzlV9NEHQcZFyVS0Lp7fqcRlSLh4beFiXeQ&oe=6AC3D2F1",
        "cat": "living",
        "title": "모험담 Living 공간 2"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/653989445_18516003919078673_3572679946882555037_n.webp?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=JsuXsxJB64IQ7kNvwEFuujL&_nc_oc=AdpEr4BdGyT87cxyT750O0caEJTGyJyoUVahTb6erRq-9VNqsIInjSDlEazsGUL2UJ4&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=5k-3-3vW8pFdTZ4v0gVdaA&_nc_ss=7f60f&oh=00_AQNpkC-92LRr2lOxIhJyJ3w6h3zBGyjalOc4JL0Dx8QGBQ&oe=6AC3D51B",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 3"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/655008744_18516133381078673_1060200973438591434_n.webp?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=109&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=tpnb7zO58AwQ7kNvwGb5bL7&_nc_oc=Adq1c_elXwy2x4Vo33G7pEzz1Hch37v9jx24qTmhwRXqmbg8ascleHhFgkyMejdZdiM&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=5k-3-3vW8pFdTZ4v0gVdaA&_nc_ss=7f60f&oh=00_AQMfZrYVimA4i0-0RNefMLVA75KPuGhCgSMBXwu2KspqjQ&oe=6AC3C188",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 4"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/727380090_1745539156882240_2862330064625513834_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=110&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=056cGdBRUIcQ7kNvwEEK3UJ&_nc_oc=Adp2Nq0M0sKiYvUCf43u5AUYiOzrgsu0D61KpbWxZczzoszfrUr2LfGVVmOGS1tCnjw&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=5k-3-3vW8pFdTZ4v0gVdaA&_nc_ss=7f60f&oh=00_AQM-W3jGxXOUQiVkQpY1awiT20bHI1UQreX6PlqreH0mIA&oe=6AC3D1CE",
        "cat": "outdoor",
        "title": "모험담 Outdoor 공간 5"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/722767574_1540600147597026_3257727041100915765_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=CK1IDDQhGxIQ7kNvwEznItZ&_nc_oc=AdoFA30xBUuBYwm1srO5-tMe46LMQSlFM6QbU7a_uSUJvJ56JxTpx1l-jYgVAl_XvZU&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=5k-3-3vW8pFdTZ4v0gVdaA&_nc_ss=7f60f&oh=00_AQOUNvoqHaCcOJ3Lkxcpk-YJH5QxTmQF6NODVk78f9nCfg&oe=6AC3C1E1",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 6"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/724092155_1065217836061794_7736140151100102202_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=102&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=ULz_mW3RoRAQ7kNvwG0MaBh&_nc_oc=AdoWm8JWrE4QUCDsgLkOEZ2EH6LWv8OFoVYfe3zy9Xf0iYyxYEDJbIAix4Vm-cyl5os&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=5k-3-3vW8pFdTZ4v0gVdaA&_nc_ss=7f60f&oh=00_AQMAx1iec_7QFiZYS3slnxnnidwf5BH3Pm_D4N5A-y7vOg&oe=6AC3CB15",
        "cat": "living",
        "title": "모험담 Living 공간 7"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/692930968_18527793319078673_6795015736541502137_n.webp?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=GNK_SfPRmNoQ7kNvwFLpaFd&_nc_oc=AdpSIS7ZYf9jfDwFjmbbqBGclfQI7mVK3YYi24z9Dy-KD7Pcc-JxS0CDO41J509R06Q&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=5k-3-3vW8pFdTZ4v0gVdaA&_nc_ss=7f60f&oh=00_AQM4Bc8o-Ol7BWzP2R2rwdpbal1oQtxW1R3348LCOFNBLg&oe=6AC3CF81",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 8"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/684344415_18524484409078673_2582063741877509992_n.webp?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=110&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=vcKvCnT5GHUQ7kNvwGvr0gw&_nc_oc=AdrEAlfs0XuDV3qafB3RvHPV0AxK2lhNl-HEzCxjk-tuIO3G91mbR7wv3gl5mXzq_d8&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=5k-3-3vW8pFdTZ4v0gVdaA&_nc_ss=7f60f&oh=00_AQOxJxCiZaG1GhD1EEIpIjh1UAWReScoWZBt4YIzznYKWw&oe=6AC3C7E7",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 9"
    }
],

  // 9. 관리자 비밀번호
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
