/**
 * 모험담 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Nightly Producer
 */

const STAY_CONFIG = {
  // 1. 브랜드 및 숙소 기본 정보
  brandName: "플루메리아 펜션",
  brandSubtitle: "Jeju Private Stay",
  tagline: "열대의 감성을 살린 트렌디한 인더스트리얼 스테이",
  description: "거친 질감의 콘크리트와 세련된 철제 가구가 빚어내는 독특한 분위기 속에서 자유를 느끼세요.",
  
  // 2. 호스트 및 연락처 정보
  owner: "호스트",
  businessNo: "",
  address: "제주 제주시 구좌읍 덕행로 377-3",
  phone: "0507-1347-3972",
  email: "contact@adopter.co.kr",
  domain: "moheomdam.adopter.co.kr",
  
  // 3. 외부 연동 링크
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1716272359/home",
  instagramUrl: "https://www.instagram.com/moheomdam",
  
  // 4. 고화질 영상 배경
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  // 5. 숙박 요금 및 연박 할인 정책
  pricing: {
    weekday: 320000,
    weekend: 350000,
    peakSurcharge: 30000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 10000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  // 6. 3대 무료 혜택
  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  // 7. 공간 구성 안내
  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  // 8. 포토 갤러리 메타데이터
  photos: [
    {
        "src": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&q=80&w=1920",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 1"
    },
    {
        "src": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&q=80&w=1920",
        "cat": "living",
        "title": "모험담 Living 공간 2"
    },
    {
        "src": "https://images.unsplash.com/photo-1599427301072-5e8348d61d19?auto=format&fit=crop&q=80&w=1920",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 3"
    },
    {
        "src": "https://images.unsplash.com/photo-1583847268964-b28ce8f52f36?auto=format&fit=crop&q=80&w=1920",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 4"
    },
    {
        "src": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&q=80&w=1920",
        "cat": "outdoor",
        "title": "모험담 Outdoor 공간 5"
    },
    {
        "src": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&q=80&w=1920",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 6"
    },
    {
        "src": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1920",
        "cat": "living",
        "title": "모험담 Living 공간 7"
    },
    {
        "src": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&q=80&w=1920",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 8"
    },
    {
        "src": "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&q=80&w=1920",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 9"
    }
],

  // 9. 관리자 비밀번호
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
