/**
 * 모험담 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Nightly Producer
 */

const STAY_CONFIG = {
  // 1. 브랜드 및 숙소 기본 정보
  brandName: "stay_handam",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "모험담에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  // 2. 호스트 및 연락처 정보
  owner: "호스트",
  businessNo: "",
  address: "제주 제주시 구좌읍 덕행로 377-3",
  phone: "0507-1347-3972",
  email: "contact@adopter.co.kr",
  domain: "moheomdam.adopter.co.kr",
  
  // 3. 외부 연동 링크
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1716272359/home",
  instagramUrl: "https://www.instagram.com/moheomdam",
  
  // 4. 고화질 영상 배경
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  // 5. 숙박 요금 및 연박 할인 정책
  pricing: {
    weekday: 320000,
    weekend: 350000,
    peakSurcharge: 30000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 10000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  // 6. 3대 무료 혜택
  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  // 7. 공간 구성 안내
  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  // 8. 포토 갤러리 메타데이터
  photos: [
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-19/441139521_1815507148941041_2449961587733718190_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=108&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDgwLkMzIn0%3D&_nc_ohc=gRC0jlFGR2oQ7kNvwFCnbHc&_nc_oc=AdpETihf20icokLfwFq09s25UeJS04gHsuJStwBTLUzEurbWtuzccK1qbfYI3PSWs9U&_nc_zt=24&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQO69EQ48jpQKzNNtwyS9y0_0e7vBKZ11YiUqpwtq8cGvg&oe=6AC3D344",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 1"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/606202957_18084284675515920_3582197221591588463_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=109&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=C1NDzzsjEC0Q7kNvwEIhSUT&_nc_oc=AdoIy8yl7mBkwMQDXM2DklL09SnkvzupKOuPX4r480xtAKoW46qefUjQu-2aUc72sEk&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=i1q_pbchBZV9NiqQfuWmyQ&_nc_ss=7f60f&oh=00_AQOb81BRaILAzWdzPwTB1udZ6eLEYalCn-CYy4mQkXYmcg&oe=6AC3D771",
        "cat": "living",
        "title": "모험담 Living 공간 2"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-15/456681012_1503550913617207_3791843531764635176_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=100&ccb=7-5&_nc_sid=acbce5&_nc_ohc=coye9xgBsQwQ7kNvwHnJxGa&_nc_oc=AdqyS-WmHpIUTtGgRdK3HizAgKEJZTKCIs0X4L7PNm2YV_SWo6L_EkN0Z2PzDMEQqa0&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQOghnCpWqQ0VhnboE7zHb3FGKMzVBp4K7unPjUKMbnhDw&oe=6AC3CB08",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 3"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/784394296_18115793726515920_2366786199345029343_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=1niac87JOEoQ7kNvwEFEyyf&_nc_oc=AdpeyEa6kKGDzinMVSGMMAmrh9CaS1dgpQferNLd9MHZPqa4aMtYLTRvuljWwAVTaJ0&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=SxpNuC3tVMSQtIqXn89VqA&_nc_ss=7f60f&oh=00_AQNWpaYUVV-okEO0NCdwrZg4WTi_1glWi0rjVDZ68TOpCw&oe=6AC3A7C7",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 4"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/670391478_18097067006515920_29386695678182566_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=111&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=3a61jVxMxDYQ7kNvwEni2dU&_nc_oc=Adr85hNHFGiUuAaE79IMhBl6Z7Chq7kn2xOci-YhgCKvPBYH0e_wBc-2xMc4o_wyqzE&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=SxpNuC3tVMSQtIqXn89VqA&_nc_ss=7f60f&oh=00_AQOw0E_dJ2w4dNwuQoe44lBI-rXvkLuXmkPDj_oggTcLKQ&oe=6AC3AC19",
        "cat": "outdoor",
        "title": "모험담 Outdoor 공간 5"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/661341257_18096149267515920_7032137205793716642_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=111&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=05Uwx8GVnIoQ7kNvwFizndq&_nc_oc=AdrvyfA8n09jTqITdGqcL0a_mXaXg7qs5zD088003XmNp7V7YuzV2urjmoWK95lTgEY&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=SxpNuC3tVMSQtIqXn89VqA&_nc_ss=7f60f&oh=00_AQP0wCdPD3cGwib-oULQ_rqfGqIlKue0crrqCWyMJIKgKg&oe=6AC3B4CE",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 6"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/640446533_18091043849515920_123571601016418166_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=106&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=lbW8HVmS1M8Q7kNvwHW4nKz&_nc_oc=Adr8nMUjrHc3tpPhz0OSaflUFv4mWewrrH6HZDbyGsg4vV7uqfvTwrGNyc0rQHdWlCE&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=SxpNuC3tVMSQtIqXn89VqA&_nc_ss=7f60f&oh=00_AQOIKXmb7vVXy3lE8RId33aM56jtzTtCYuKPmqmcHl_J5A&oe=6AC3D1CE",
        "cat": "living",
        "title": "모험담 Living 공간 7"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/627636747_18089524244515920_5684971574456123133_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=0eHjgwhatcIQ7kNvwGem-mL&_nc_oc=AdpXt9lzcx3JZtbM1ZdkCspUlM2XCM4IuecDjBnORuVeiGgFi44XMPq4PPy_gVgP0UI&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=SxpNuC3tVMSQtIqXn89VqA&_nc_ss=7f60f&oh=00_AQNTi0OYSLwOtZrXBd7xM7bcW_ODmi8NNldVw1ZaCK_qHg&oe=6AC3B376",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 8"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/625001501_18088261988515920_8041979387412777717_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=111&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=kOC53BuFbIoQ7kNvwHcadyQ&_nc_oc=Adp_ju9HBnAQhj0Yaw0kDxqZCZOuNFBMnTpty_dbiLDLLqKQ3g0hJddIMx1ueOX2HdY&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=SxpNuC3tVMSQtIqXn89VqA&_nc_ss=7f60f&oh=00_AQNcp2GecbqJTUdnHC6c7jRE9GUcQzbPaM1v-k2kKKCU3g&oe=6AC3DD93",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 9"
    }
],

  // 9. 관리자 비밀번호
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
