/**
 * 한림 몽돌하우스 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Autonomous Producer
 */

const STAY_CONFIG = {
  brandName: "한림 몽돌하우스",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "한림 몽돌하우스에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  owner: "호스트",
  businessNo: "",
  address: "제주특별자치도",
  phone: "",
  email: "contact@adopter.co.kr",
  domain: "mongdol.adopter.co.kr",
  
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/2576795/home",
  instagramUrl: "",
  
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  pricing: {
    weekday: 300000,
    weekend: 340000,
    peakSurcharge: 40000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 20000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  photos: [],
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
