/**
 * 모험담 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Nightly Producer
 */

const STAY_CONFIG = {
  // 1. 브랜드 및 숙소 기본 정보
  brandName: "chungchun_yeonga",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "모험담에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  // 2. 호스트 및 연락처 정보
  owner: "호스트",
  businessNo: "",
  address: "제주 제주시 구좌읍 덕행로 377-3",
  phone: "0507-1347-3972",
  email: "contact@adopter.co.kr",
  domain: "moheomdam.adopter.co.kr",
  
  // 3. 외부 연동 링크
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1716272359/home",
  instagramUrl: "https://www.instagram.com/moheomdam",
  
  // 4. 고화질 영상 배경
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  // 5. 숙박 요금 및 연박 할인 정책
  pricing: {
    weekday: 320000,
    weekend: 350000,
    peakSurcharge: 30000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 10000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  // 6. 3대 무료 혜택
  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  // 7. 공간 구성 안내
  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  // 8. 포토 갤러리 메타데이터
  photos: [
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-19/656627399_17986024175959988_3640934010994304643_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=100&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDI0LkMzIn0%3D&_nc_ohc=g00G-Xcvl6cQ7kNvwEB_FhL&_nc_oc=Adoss6g_A-i2mavILG6k8s_K_slL0zYAl-tZz00SPof5iUD4PZXDHkZzZofaYFoMP94&_nc_zt=24&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Xyqm7gRgwk9hCQoUZ2bPZQ&_nc_ss=7f60f&oh=00_AQMVqSLVFW0v03kPIhQUYWy7TLh2_puBiHrOuVWfoO-iZA&oe=6AC3DB8F",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 1"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/798590286_926690720025680_7907281349825535327_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=102&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=5dSfKZROTfEQ7kNvwHB0BYA&_nc_oc=AdrGgkXqG38toeUBCdkuyMTxI8y5mBML03e1jF3LNqsU9oib7FEYitJ_u0PXKXh81t4&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Xyqm7gRgwk9hCQoUZ2bPZQ&_nc_ss=7f60f&oh=00_AQOi7N2GKVeJrq2s3gLtMMjyNUfH5gL-qk8ojjMXiW1V7A&oe=6AC3CF39",
        "cat": "living",
        "title": "모험담 Living 공간 2"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/729969219_1805768220399665_3320238062294346659_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=109&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=qshg-pVi6icQ7kNvwFp7j8q&_nc_oc=AdoVQ7nG25kVvwAMy29yTDYxMe3lRLaEQwEsXOtbw1UbCKJdqQFJ4KpodPUnwJ_kskE&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Xyqm7gRgwk9hCQoUZ2bPZQ&_nc_ss=7f60f&oh=00_AQOYZug-Ze5Qidqyg-EWJT8BUp-5etfJRvrIZNCgBwSz0A&oe=6AC3D47D",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 3"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/762650961_18608063413039403_5249195713382812302_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=G7g6WdDjSYkQ7kNvwH_t_hS&_nc_oc=AdrSyz3ihIVQTnXqVQcGKGY-peH0FRWnHw1PnE1loAQjjX8gtIH7n8JZhnCfnRHpZMY&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Xyqm7gRgwk9hCQoUZ2bPZQ&_nc_ss=7f60f&oh=00_AQNlEZoB-jgwc_HyivesW8KWkvavFK3PuMn7ee-7P6Vulg&oe=6AC3B650",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 4"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/734747253_17999273672959988_406918070140158936_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=tHI3Xo8MgWcQ7kNvwEuQ1gz&_nc_oc=AdrkW7umTJL_WM3vqvUwruX2qL19Pilrhug1iwhPzYblpS17BugKCz_lrek-ZpAYKtw&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Xyqm7gRgwk9hCQoUZ2bPZQ&_nc_ss=7f60f&oh=00_AQNTnI_Cltbh9CIvEK3IK-iDt6q3n5CR2xI_aPwIfjieKQ&oe=6AC3CCD5",
        "cat": "outdoor",
        "title": "모험담 Outdoor 공간 5"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/718238081_17995273019959988_3022661859646056031_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=102&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=ICLL6m76-4YQ7kNvwEUaE-D&_nc_oc=Adp99-0o2rzyftHc1Q_VMFd7S4YY3tjnbrvH-8ZnU7DOhwZhRS-hKC_9JiqwmPu4Rp4&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Xyqm7gRgwk9hCQoUZ2bPZQ&_nc_ss=7f60f&oh=00_AQPjuATKzGactNFl5xUgxJpsVN0LgsYl3BDswXDIojeaqw&oe=6AC3D2E9",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 6"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/542229677_24467273789625770_4317347322975018060_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=108&ccb=7-5&_nc_sid=acbce5&_nc_ohc=3OFdrDHjKA4Q7kNvwG582GO&_nc_oc=AdoqyQSzlQCnntp2FcTfogfw3kz5Uor88LQkCcWEPCmU1TG-8ZmSq4z8P5kZn9lG5wc&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Xyqm7gRgwk9hCQoUZ2bPZQ&_nc_ss=7f60f&oh=00_AQOK4YSP991p08O-90X6hkPKgaGvkuRvuw6Z7Hd0QqY3vQ&oe=6AC3AA31",
        "cat": "living",
        "title": "모험담 Living 공간 7"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/684229937_1482318023333070_7947276930561864250_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=108&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=nVm8oNWadusQ7kNvwGpp870&_nc_oc=Ado0K-lxfRAjAp8iT3rPLl6Vuzpd69K3IOJn7SN-N4tsQKIMvr0oxGINcpRCB2BPr0g&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Xyqm7gRgwk9hCQoUZ2bPZQ&_nc_ss=7f60f&oh=00_AQN6gFoHLDQQayJVKaTDygHhw9xmGN3WdzvO16fpetsH_w&oe=6AC3D82E",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 8"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/635048983_2057791948334185_7675864386833597810_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=102&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=fTPZ-uXLiooQ7kNvwH0w6CX&_nc_oc=AdrIWdFA3u01WywSQa7l3aplcjtVasK0a4aykTWjzMsFH7KoIgzDyzO0PB8_uhIOqcc&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=Xyqm7gRgwk9hCQoUZ2bPZQ&_nc_ss=7f60f&oh=00_AQOENLPeOevZ6hNwoF8-TUZxn5qRNNMqMYOMi6MXHimMGA&oe=6AC3CDE0",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 9"
    }
],

  // 9. 관리자 비밀번호
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
