/**
 * 모험담 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Nightly Producer
 */

const STAY_CONFIG = {
  // 1. 브랜드 및 숙소 기본 정보
  brandName: "스테이느긋",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "모험담에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  // 2. 호스트 및 연락처 정보
  owner: "호스트",
  businessNo: "",
  address: "제주 제주시 구좌읍 덕행로 377-3",
  phone: "0507-1347-3972",
  email: "contact@adopter.co.kr",
  domain: "moheomdam.adopter.co.kr",
  
  // 3. 외부 연동 링크
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1716272359/home",
  instagramUrl: "https://www.instagram.com/moheomdam",
  
  // 4. 고화질 영상 배경
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  // 5. 숙박 요금 및 연박 할인 정책
  pricing: {
    weekday: 320000,
    weekend: 350000,
    peakSurcharge: 30000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 10000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  // 6. 3대 무료 혜택
  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  // 7. 공간 구성 안내
  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  // 8. 포토 갤러리 메타데이터
  photos: [
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-19/773541635_18003599243974402_213636373424309562_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=109&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDA4LkMzIn0%3D&_nc_ohc=3FAbMG5-hC8Q7kNvwHsDRqU&_nc_oc=AdpuYZDzlBDQ8Dh3Wk6LVGvmXLaACrp7uXw911FkIc1QvbSfcnUVT0QBb3rNHqGdhWo&_nc_zt=24&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=8oku2SKEFrTpX6RLVKjHag&_nc_ss=7f60f&oh=00_AQMOpCxLjZVzTwoULFQcS-CUtF7qKSHxergZTFGd0uObRw&oe=6AC3DB80",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 1"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/773028722_18003600572974402_7263025395186197204_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=110&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=q-O0YMIJnK4Q7kNvwEDW2H0&_nc_oc=AdrR9Nu2IcS_xFYfn-wkpqADuHkyoJtN98qZJJpDKyEAYdHVunIvxAWSYwYXq0h7AbU&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=eBSMPNv5E7LuaCqh6TX7lQ&_nc_ss=7f60f&oh=00_AQM57kUNO0tEmh8t70xn_8FMvDyFXlLx-17M5Lht2MEqmg&oe=6AC3D6DB",
        "cat": "living",
        "title": "모험담 Living 공간 2"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/772707685_18003601388974402_4699916695801521852_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=w-81FW_EM8oQ7kNvwF58fJ3&_nc_oc=AdqKtXQ4660tt8D4gAi6dOfnzTekcTXDwyU6os0QzuPq_FwFDjSD7yqXTcCui-WO_zM&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=eBSMPNv5E7LuaCqh6TX7lQ&_nc_ss=7f60f&oh=00_AQOyAY-_YzppZmepv2StdAYCVausVhpghoc_z0XDZp9kHg&oe=6AC3B74F",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 3"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/773928961_18003607454974402_3032277722398164543_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=108&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=wE-cscXO_ckQ7kNvwFmWi7Y&_nc_oc=Adr6bmLJ3ayO-Bu0EMVGRTKtdFpw1aBXwFctSIs1MicYT-rOmS2NpanFk1bTXoz4gkE&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=eBSMPNv5E7LuaCqh6TX7lQ&_nc_ss=7f60f&oh=00_AQMG09RPvekzMdlSo_5mRhpyJk_CGV3KW_JFJS92f-gp6g&oe=6AC3AB0A",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 4"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/829555576_1592175765989331_6625252372994292848_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=Znm39ykTEKgQ7kNvwFK2Umf&_nc_oc=Adq1zHQAKlvE_gjG4IAI8r50WC5hVtWgbVlnGqjlS8dXYUga7ySKzEO3B1UioNDpk4k&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=eBSMPNv5E7LuaCqh6TX7lQ&_nc_ss=7f60f&oh=00_AQP8lJq9SSuqjDGmJIy6CbmtzKAO_B-70BpHfA2n1RjE3A&oe=6AC3C8FF",
        "cat": "outdoor",
        "title": "모험담 Outdoor 공간 5"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/818491895_18009663026974402_3782816314658140538_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=104&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=SQ0M1Codwx8Q7kNvwE3uUqa&_nc_oc=AdomNDLWD91UW2IQL3j9IOhjadb-b6GNxnpOH7z8siI0BZtjeudysJ5Tvey_p67kdeY&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=eBSMPNv5E7LuaCqh6TX7lQ&_nc_ss=7f60f&oh=00_AQN7Q9x-qZbhI9sN_el9Ik4kKDIYc9BBs2qlrMKgZhMdZA&oe=6AC3B3E3",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 6"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/825323294_18010473584974402_1263190011928572778_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=111&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=UXnKAK_YLU4Q7kNvwGuCezI&_nc_oc=AdrqsIugSHXOIwWRo_AHnqL4CTqB_k5Uc4-Nd75yajK2nndof_DeL5F9Tfw1Tuzhp18&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=eBSMPNv5E7LuaCqh6TX7lQ&_nc_ss=7f60f&oh=00_AQNxTaBAIlDY3U-G75G_eeyDH9apHCxkWiPNNPh94aCoSg&oe=6AC3CE97",
        "cat": "living",
        "title": "모험담 Living 공간 7"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/825269474_963277486134835_3032899502783801812_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=106&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=8bSGWJwNSqkQ7kNvwGnE2k7&_nc_oc=AdpqMNbo4YQdmHU_rnwJlVp5cxo5bJqvLTCtcqtwsxc57PFnCz6j_Dk2bHLp2HmdpS4&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=eBSMPNv5E7LuaCqh6TX7lQ&_nc_ss=7f60f&oh=00_AQOycl2WVUgCZwxx94SM77Lx7UXFFaY-3beQQDEYHHDmvg&oe=6AC3B37B",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 8"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/819776277_18009947507974402_3121690018726609940_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=100&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=oRUaEvOdnIEQ7kNvwEzTbkc&_nc_oc=Adori9AYiz_YTxx19oKoOPqOJ6MvoQvIldOiA-StmOjfwBa6bX_7u0WE6K0wuyzsupI&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=eBSMPNv5E7LuaCqh6TX7lQ&_nc_ss=7f60f&oh=00_AQOGrPKok6CcI7DV2OCVQtblHwYE1bEpe0lpjf49MlNgbQ&oe=6AC3DAC0",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 9"
    }
],

  // 9. 관리자 비밀번호
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
