/**
 * 모험담 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Nightly Producer
 */

const STAY_CONFIG = {
  // 1. 브랜드 및 숙소 기본 정보
  brandName: "곁겹",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "모험담에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  // 2. 호스트 및 연락처 정보
  owner: "호스트",
  businessNo: "",
  address: "제주 제주시 구좌읍 덕행로 377-3",
  phone: "0507-1347-3972",
  email: "contact@adopter.co.kr",
  domain: "moheomdam.adopter.co.kr",
  
  // 3. 외부 연동 링크
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1716272359/home",
  instagramUrl: "https://www.instagram.com/moheomdam",
  
  // 4. 고화질 영상 배경
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  // 5. 숙박 요금 및 연박 할인 정책
  pricing: {
    weekday: 320000,
    weekend: 350000,
    peakSurcharge: 30000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 10000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  // 6. 3대 무료 혜택
  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  // 7. 공간 구성 안내
  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  // 8. 포토 갤러리 메타데이터
  photos: [
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-19/610174468_18038000843724940_6202007750375666359_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=100&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy41OTIuQzMifQ%3D%3D&_nc_ohc=PsdcWANDW1IQ7kNvwGgHOqp&_nc_oc=AdoPR0d1de6s867hP5JgpT464tPR68bjTxosObb8ZiTP1myvFhSnAVxOOXxYgGKwHbk&_nc_zt=24&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=mYVLe0KCH4ASfby6F8wjqw&_nc_ss=7f60f&oh=00_AQNvgiq3vPEUIOrN6m7qJJe0k7P6hEqI-zPg6H3gjFdRYA&oe=6AC3B200",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 1"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/587477509_18135085807479262_9213673882013600635_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=101&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=wjYyAdaoQqMQ7kNvwHr3vg6&_nc_oc=AdodiRrplrlkX9nG1-lCEKIT10pRDUcGOP6HI6u4aJLNzqDwQFNhCvYqH-8m3N98ugE&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=mYVLe0KCH4ASfby6F8wjqw&_nc_ss=7f60f&oh=00_AQMJphUApCler9sPEVOPHXGmsQIBy8q8wabfu1tEJcAPkQ&oe=6AC3C705",
        "cat": "living",
        "title": "모험담 Living 공간 2"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/566667717_18102340972651949_4802650748103419139_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=107&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=poXV-RmZB-oQ7kNvwEPt5d1&_nc_oc=AdoVb901pAR1OUXFJ8eEFBCcc2yfWcwXcm-LfPIT9byRx05Pkxu7dKxGBc0V1SX3rc4&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=mYVLe0KCH4ASfby6F8wjqw&_nc_ss=7f60f&oh=00_AQMlVvnUHzXxnd_yIgWG26c3aJ8VJKbY1VP4R8caKgU3kA&oe=6AC3B91C",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 3"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.2885-15/303868469_410397201004736_3804438693841008677_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=100&ccb=7-5&_nc_sid=acbce5&_nc_ohc=MoC0VlX72RUQ7kNvwFXBvbR&_nc_oc=Adp8LEgpAprSBzp0sfhml5ocEeGDDf2454F76tJ1LQnGKWu1bXSvRBUtqpxA7vqCWWo&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_ss=7f60f&oh=00_AQMAoWC0y0LZl7qsqQkqrxb6Ty9VLjlZwnRKg3_tiut--g&oe=6AC3A9A1",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 4"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/562172908_18069373175009936_1191509788450623244_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=AwiV1FAkU08Q7kNvwGNFqZG&_nc_oc=AdrsAnkzid60U7gwch5ajPvwgvRosclfohjDw5MY5oKzCwREflOJWgD0LgYnEU641oA&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=mYVLe0KCH4ASfby6F8wjqw&_nc_ss=7f60f&oh=00_AQPwNbSEk7bDPnA7VStcNwB62ChJuC411Y-R4VtS1UZ4lw&oe=6AC3D623",
        "cat": "outdoor",
        "title": "모험담 Outdoor 공간 5"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/568528896_18324506758241609_8506155998438583808_n.jpg?stp=c0.5x0.5f_dst-jpg_e35_p150x150_tt6_u&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiU1RPUlkuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=ZmD_NXewgjcQ7kNvwE21kdC&_nc_oc=AdrGVSh0QgFCclDziIgrDI7lleixVhFjqmJfXjo3IpLhs5ZWVgmRki6g2AuZo10ntdM&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=mYVLe0KCH4ASfby6F8wjqw&_nc_ss=7f60f&oh=00_AQOm95gBtLvuZujp5T0CLhZmSZnnk-wSj0DmUEb20gKOUg&oe=6AC3C4EE",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 6"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/502756602_938648804986031_7910053978243701905_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=102&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=iFuQVaLQdBwQ7kNvwEuOqbf&_nc_oc=Adq32UZA0t_vqOZvFLpvEQFAUaytqwhfjnYRDKR93Q-grnCY2U7pGlGD1p80vWpLRXE&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=tLHnb0BK-0iJ2ag7z6NB7w&_nc_ss=7f60f&oh=00_AQPh1JZBmb1R0vfTPwMMU7KULIXqtSFgChIAnqy7pHLXFQ&oe=6AC3DD49",
        "cat": "living",
        "title": "모험담 Living 공간 7"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/621847417_18078017450339908_8976812971852901284_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=106&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=LbY9b07G_8EQ7kNvwGavsGL&_nc_oc=AdpUgzL9T1MfcYd48yU_bOtUgAeoT3JYiHAPL9UV0XH2atv2LEO6d1cLg0SCjdqxZdw&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=tLHnb0BK-0iJ2ag7z6NB7w&_nc_ss=7f60f&oh=00_AQN3uPuXyOFgtxWQekqtgg-5Wfq1YRazzXYFAAbWTi97QQ&oe=6AC3CF44",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 8"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t39.30808-6/468049487_17992323773724940_6936204064672471425_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=108&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=VVZWfQxlTX0Q7kNvwFzACmD&_nc_oc=AdrTaImMbAsIz6yEwI59uk1NSBu_8UIiFl4Gdw1-FjT0c_0loYRvlFCXhrAr11BIgX0&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=tLHnb0BK-0iJ2ag7z6NB7w&_nc_ss=7f60f&oh=00_AQNWWep3vP1UwXLyUNRhLRFAvO_ZBO9SsuOWUCo-05XhCw&oe=6AC3B58F",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 9"
    }
],

  // 9. 관리자 비밀번호
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
