/**
 * 모험담 공식 웹사이트 설정 데이터
 * Auto-generated by Adopter Nightly Producer
 */

const STAY_CONFIG = {
  // 1. 브랜드 및 숙소 기본 정보
  brandName: "사누르제주",
  brandSubtitle: "Jeju Private Stay",
  tagline: "머묾, 그 자체가 온전한 쉼이 되는 곳",
  description: "모험담에서 전하는 온전하고 프라이빗한 쉼. 제주의 자연과 돌담이 어우러진 아름다운 공간.",
  
  // 2. 호스트 및 연락처 정보
  owner: "호스트",
  businessNo: "",
  address: "제주 제주시 구좌읍 덕행로 377-3",
  phone: "0507-1347-3972",
  email: "contact@adopter.co.kr",
  domain: "moheomdam.adopter.co.kr",
  
  // 3. 외부 연동 링크
  kakaoChatUrl: "http://pf.kakao.com/_HCTxiX/chat",
  naverMapUrl: "https://m.place.naver.com/accommodation/1716272359/home",
  instagramUrl: "https://www.instagram.com/moheomdam",
  
  // 4. 고화질 영상 배경
  youtubeIntroId: "f09Xfn1fHm8",
  youtubeTourId: "JG92-0fSScQ",
  
  // 5. 숙박 요금 및 연박 할인 정책
  pricing: {
    weekday: 320000,
    weekend: 350000,
    peakSurcharge: 30000,
    baseGuests: 4,
    maxGuests: 8,
    extraGuestFee: 10000,
    minNights: 2,
    discounts: {
      days7: 10,
      days14: 15,
      days28: 20
    },
    depositLessThan7: 200000,
    depositMoreThan7: 300000,
    depositMoreThan28: 500000
  },

  // 6. 3대 무료 혜택
  freeBenefits: [
    { title: "프라이빗 정원 & 테라스", subtitle: "Garden", desc: "단독 정원 및 야외 휴식 공간 완비" },
    { title: "사계절 전용 바베큐", subtitle: "BBQ", desc: "독립 다이닝 공간 및 그릴 무료 완비" },
    { title: "안락한 쉼과 온수", subtitle: "Relax", desc: "편안한 프리미엄 침구 및 쾌적한 전용 시설" }
  ],

  // 7. 공간 구성 안내
  spaces: {
    landSize: "120평 대지",
    buildingSize: "35평 단독주택",
    floor1: "거실, 풀옵션 주방, 마스터룸, 온돌룸, 욕실, 파우더룸",
    outdoor: "프라이빗 정원, 야외 테라스, 개별 바베큐장, 전용 주차공간"
  },

  // 8. 포토 갤러리 메타데이터
  photos: [
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-19/516231302_17842797711533506_5494889003019142234_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=108&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDgwLkMzIn0%3D&_nc_ohc=Td0uAzHUTmsQ7kNvwFdf38X&_nc_oc=AdoWHHe8bXSmhnjCwobLxVkld8F7poqQolr_DZ2F2eMpw0GzAmnWSW1M0-WiYkbgKUI&_nc_zt=24&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=jOQXfUD8GlAsabRGXGDbSQ&_nc_ss=7e60f&oh=00_AQPw9iWz_Zrz-6-KDREeC4nIL8zVEX1NbNYMC2z6t1TbtA&oe=6AC3D166",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 1"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/573043194_17860039674533506_6793652485887044592_n.heic?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=107&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=2BnQ_IVpYQAQ7kNvwHuuhLQ&_nc_oc=AdpDyN6emzOnQ9-Ls_jpE-Pj8NJbu1K4oxyubHuhQ1U6mxK2jFwq8hzO3SGHzVlQvDo&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=BXQSGgVTNmFuDMCVdO8wBA&_nc_ss=7e60f&oh=00_AQNCHmr4QmoJh_1SFVoDX-XeQM8GKcYWkvARpqCRIetsNA&oe=6AC3D6F3",
        "cat": "living",
        "title": "모험담 Living 공간 2"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/670271581_18076536458399851_2869528731248141916_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=104&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=hPJ3cfhvMCgQ7kNvwHzkDGn&_nc_oc=AdrHiNMszLTQ7I8p_kYjChnsvW5EVQZts4rWOeoFzwFNhPKQDhJhVQ2e9xi-RNn1G04&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=BXQSGgVTNmFuDMCVdO8wBA&_nc_ss=7e60f&oh=00_AQOid6F-N3Xi8RGfU_LqLKR8UIaqgFAe9EXCIhPP4osnaQ&oe=6AC3D163",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 3"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/655713001_18097132648824523_4417946173517841456_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=103&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=gqgbBWDQOMwQ7kNvwFjwFsy&_nc_oc=Adrn-XauqHwryXLISjVyrxLaPfhBs46_2r9CsQhJzXeiUlf47Gq8AynM24jm4Z8GyFQ&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=BXQSGgVTNmFuDMCVdO8wBA&_nc_ss=7e60f&oh=00_AQMuca2mMAMkAkD-vRTfd3K8pwt43H3oEIyNF1mVbw-5Mw&oe=6AC3D55C",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 4"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/655447175_18073006352208138_4603351665860847966_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=109&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0FST1VTRUxfSVRFTS5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=IMM4Q3m2NkAQ7kNvwH5eSqL&_nc_oc=Adopx6RV_RnIlDoAUcxBRAsBc8Il30y5305uN_8ta1YJ-rASgFAJWpr5kxpxT3M9ymw&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=BXQSGgVTNmFuDMCVdO8wBA&_nc_ss=7e60f&oh=00_AQOWBV_lvSpvTgtCI7ocxY5DVGYfW79E5l4EWkiy8Cf40Q&oe=6AC3BD4A",
        "cat": "outdoor",
        "title": "모험담 Outdoor 공간 5"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/518344512_637814165994346_8994699287420194711_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=106&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=b2jjEFLuyD0Q7kNvwGEghJ4&_nc_oc=AdpGYcOWZWqRoreUDYLLPxzfvFNGC7o44aXs0KlmjCUnjEQUu3oGFLmqckivWXTlVos&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=BXQSGgVTNmFuDMCVdO8wBA&_nc_ss=7e60f&oh=00_AQMi0l8g_a0rMftZNX8AY_oO0XNFriCaC-4scmZcKuhUHQ&oe=6AC3CAE0",
        "cat": "exterior",
        "title": "모험담 Exterior 공간 6"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-15/625040934_18080725436252903_9101187907308861954_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=102&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiRkVFRC5iZXN0X2ltYWdlX3VybGdlbi5DMyJ9&_nc_ohc=R8QGA_OvkNwQ7kNvwGBNVCD&_nc_oc=AdrvMHVkyS3PBr_A15eHCyCnRNkPojFEaUU8yVboqKA2Xc9zhKro5djK2BzUf_SFaPA&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=BXQSGgVTNmFuDMCVdO8wBA&_nc_ss=7e60f&oh=00_AQMVCPngRFg2PW8JKvYHMACDetSB4UbydY_bYgsGobyJOQ&oe=6AC3DB3B",
        "cat": "living",
        "title": "모험담 Living 공간 7"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.71878-15/516376406_1424608015446207_2474038549130558681_n.jpg?stp=dst-jpg_e35_s640x640_tt6&_nc_cat=105&ccb=7-5&_nc_sid=18de74&efg=eyJlZmdfdGFnIjoiQ0xJUFMuYmVzdF9pbWFnZV91cmxnZW4uQzMifQ%3D%3D&_nc_ohc=GPt0MgnNMgIQ7kNvwGlPKuY&_nc_oc=Adr_FgpgHCp4WY-q7PNmj60WlybE2TTrWpnVoXa65r4k2KLOiQvqwOHb_-ljK-WQ_rg&_nc_zt=23&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=BXQSGgVTNmFuDMCVdO8wBA&_nc_ss=7e60f&oh=00_AQOL60XbdSQODGNSa8LqdH8mtYcrZPk2YZ47LdRFxq0SZQ&oe=6AC3B9FE",
        "cat": "bedroom",
        "title": "모험담 Bedroom 공간 8"
    },
    {
        "src": "https://scontent-icn2-1.cdninstagram.com/v/t51.82787-19/516231302_17842797711533506_5494889003019142234_n.jpg?stp=dst-jpg_s150x150_tt6&_nc_cat=108&ccb=7-5&_nc_sid=f7ccc5&efg=eyJ2ZW5jb2RlX3RhZyI6InByb2ZpbGVfcGljLnd3dy4xMDgwLkMzIn0%3D&_nc_ohc=Td0uAzHUTmsQ7kNvwFdf38X&_nc_oc=AdoWHHe8bXSmhnjCwobLxVkld8F7poqQolr_DZ2F2eMpw0GzAmnWSW1M0-WiYkbgKUI&_nc_zt=24&_nc_ht=scontent-icn2-1.cdninstagram.com&_nc_gid=jOQXfUD8GlAsabRGXGDbSQ&_nc_ss=7e60f&oh=00_AQPw9iWz_Zrz-6-KDREeC4nIL8zVEX1NbNYMC2z6t1TbtA&oe=6AC3D166",
        "cat": "kitchen",
        "title": "모험담 Kitchen 공간 9"
    }
],

  // 9. 관리자 비밀번호
  adminPassword: "1316"
};

if (typeof module !== 'undefined' && module.exports) {
  module.exports = STAY_CONFIG;
}
